# Generated by Django 2.1.15 on 2021-05-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traitchoicesability',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
