# Generated by Django 3.2.4 on 2021-06-19 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0005_auto_20210530_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartingProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.SmallIntegerField()),
                ('toughness', models.SmallIntegerField()),
                ('movement', models.SmallIntegerField()),
                ('martial', models.SmallIntegerField()),
                ('ranged', models.SmallIntegerField()),
                ('defense', models.SmallIntegerField()),
                ('discipline', models.SmallIntegerField()),
                ('willpower', models.SmallIntegerField()),
                ('command', models.SmallIntegerField()),
                ('wounds', models.SmallIntegerField()),
                ('attacks', models.SmallIntegerField()),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('H', 'Huge'), ('C', 'Colossal')], max_length=2)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='FactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('is_default', models.BooleanField()),
                ('age', models.SmallIntegerField()),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.domain')),
            ],
        ),
        migrations.CreateModel(
            name='CategorySlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.SmallIntegerField()),
                ('max', models.SmallIntegerField()),
                ('object_id', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
